<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="1" tests="1" time="4.326349496841431">
	<testsuite disabled="0" errors="0" failures="1" name="meraki_ms_link_aggregation-xnl5a9qa" skipped="0" tests="1" time="4.326349496841431">
		<testcase classname="/root/ansible/ansible_collections/cisco/meraki/tests/output/.tmp/integration/meraki_ms_link_aggregation-wfqawttq-ÅÑŚÌβŁÈ/tests/integration/targets/meraki_ms_link_aggregation/tasks/main.yml:64" name="[localhost] meraki: meraki_ms_link_aggregation : Update LAG with idempotency auth_key={{auth_key}}, state=present, org_name={{test_org_name}}, net_name={{test_switch_net_name}}, lag_id=MTE3MTA2MDdfMA==, switch_ports=[{'serial': '{{serial_switch}}', 'port_id': '1'}, {'serial': '{{serial_switch}}', 'port_id': '2'}, {'serial': '{{serial_switch}}', 'port_id': '3'}, {'serial': '{{serial_switch}}', 'port_id': '4'}]" time="4.326349">
			<failure message="Provided lag_id is not valid." type="failure">{
&quot;ansible_facts&quot;: {
&quot;discovered_interpreter_python&quot;: &quot;/usr/bin/python&quot;
},
&quot;changed&quot;: false,
&quot;deprecations&quot;: [
{
&quot;msg&quot;: &quot;Distribution Ubuntu 18.04 on host localhost should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information&quot;,
&quot;version&quot;: &quot;2.12&quot;
}
],
&quot;msg&quot;: &quot;Provided lag_id is not valid.&quot;,
&quot;response&quot;: &quot;OK (unknown bytes)&quot;,
&quot;status&quot;: 200
}</failure>
		</testcase>
	</testsuite>
</testsuites>
