{
    "docs": "https://docs.ansible.com/ansible/2.9/dev_guide/testing/sanity/compile.html",
    "results": [
        {
            "message": "The test `ansible-test sanity --test compile --python 2.6` [[explain](https://docs.ansible.com/ansible/2.9/dev_guide/testing/sanity/compile.html)] failed with 40 errors:",
            "output": "venv/lib/python3.7/site-packages/pip/_internal/build_env.py:71:38: SyntaxError: os.path.normcase(site) for site in (\nvenv/lib/python3.7/site-packages/pip/_internal/cache.py:43:35: SyntaxError: _valid_formats = {\"source\", \"binary\"}\nvenv/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py:103:48: SyntaxError: binary_only = FormatControl(set(), {':all:'})\nvenv/lib/python3.7/site-packages/pip/_internal/cli/parser.py:157:37: SyntaxError: section_items = {name: [] for name in override_order}\nvenv/lib/python3.7/site-packages/pip/_internal/commands/__init__.py:44:30: SyntaxError: commands_dict = {c.name: c for c in commands_order}\nvenv/lib/python3.7/site-packages/pip/_internal/commands/download.py:115:53: SyntaxError: with RequirementTracker() as req_tracker, TempDirectory(\nvenv/lib/python3.7/site-packages/pip/_internal/commands/freeze.py:12:18: SyntaxError: DEV_PKGS = {'pip', 'setuptools', 'distribute', 'wheel'}\nvenv/lib/python3.7/site-packages/pip/_internal/commands/install.py:308:53: SyntaxError: with RequirementTracker() as req_tracker, TempDirectory(\nvenv/lib/python3.7/site-packages/pip/_internal/commands/list.py:178:23: SyntaxError: return {pkg for pkg in packages if pkg.key not in dep_keys}\nvenv/lib/python3.7/site-packages/pip/_internal/commands/wheel.py:121:53: SyntaxError: with RequirementTracker() as req_tracker, TempDirectory(\nvenv/lib/python3.7/site-packages/pip/_internal/configuration.py:134:27: SyntaxError: variant: [] for variant in self._override_order\nvenv/lib/python3.7/site-packages/pip/_internal/index.py:137:29: SyntaxError: if scheme not in {'http', 'https'}:\nvenv/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py:102:35: SyntaxError: _allowed_strategies = {\"eager\", \"only-if-needed\", \"to-satisfy-only\"}\nvenv/lib/python3.7/site-packages/pip/_internal/models/format_control.py:58:27: SyntaxError: result = {\"binary\", \"source\"}\nvenv/lib/python3.7/site-packages/pip/_internal/pep425tags.py:108:35: SyntaxError: if not soabi and impl in {'cp', 'pp'} and hasattr(sys, 'maxunicode'):\nvenv/lib/python3.7/site-packages/pip/_internal/req/req_install.py:100:51: SyntaxError: pkg_resources.safe_extra(extra) for extra in req.extras\nvenv/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py:196:37: SyntaxError: os.path.join(folder, \"*\") for folder in folders\nvenv/lib/python3.7/site-packages/pip/_internal/utils/compat.py:235:24: SyntaxError: stdlib_pkgs = {\"python\", \"wsgiref\", \"argparse\"}\nvenv/lib/python3.7/site-packages/pip/_internal/utils/misc.py:1062:29: SyntaxError: reverse = {value: key for key, value in enums.items()}\nvenv/lib/python3.7/site-packages/pip/_internal/wheel.py:212:31: SyntaxError: parent_dir: scripts for parent_dir, scripts in grouped_by_dir.items()\nvenv/lib/python3.7/site-packages/pip/_vendor/cachecontrol/adapter.py:13:34: SyntaxError: invalidating_methods = {\"PUT\", \"DELETE\"}\nvenv/lib/python3.7/site-packages/pip/_vendor/cachecontrol/heuristics.py:101:12: SyntaxError: 200, 203, 204, 206, 300, 301, 404, 405, 410, 414, 501\nvenv/lib/python3.7/site-packages/pip/_vendor/html5lib/_trie/_base.py:19:21: SyntaxError: return {x for x in keys if x.startswith(prefix)}\nvenv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py:176:35: SyntaxError: 'get_requires_for_build_wheel',\nvenv/lib/python3.7/site-packages/pip/_vendor/pytoml/test.py:13:44: SyntaxError: return { k: translate_to_test(v) for k, v in v.items() }\nvenv/lib/python3.7/site-packages/pip/_vendor/requests/adapters.py:132:51: SyntaxError: return {attr: getattr(self, attr, None) for attr in self.__attrs__}\nvenv/lib/python3.7/site-packages/pip/_vendor/requests/hooks.py:18:25: SyntaxError: return {event: [] for event in HOOKS}\nvenv/lib/python3.7/site-packages/pip/_vendor/requests/models.py:655:51: SyntaxError: return {attr: getattr(self, attr, None) for attr in self.__attrs__}\nvenv/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py:750:52: SyntaxError: state = {attr: getattr(self, attr, None) for attr in self.__attrs__}\nvenv/lib/python3.7/site-packages/pip/_vendor/urllib3/connectionpool.py:93:33: SyntaxError: _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}\nvenv/lib/python3.7/site-packages/pip/_vendor/urllib3/fields.py:74:7: SyntaxError: for cc\nvenv/lib/python3.7/site-packages/pip/_vendor/urllib3/packages/backports/makefile.py:19:29: SyntaxError: if not set(mode) <= {\"r\", \"w\", \"b\"}:\nvenv/lib/python3.7/site-packages/pip/_vendor/urllib3/packages/rfc3986/validators.py:172:31: SyntaxError: component: True for component in components\nvenv/lib/python3.7/site-packages/pip/_vendor/urllib3/request.py:39:36: SyntaxError: _encode_url_methods = {'DELETE', 'GET', 'HEAD', 'OPTIONS'}\nvenv/lib/python3.7/site-packages/pip/_vendor/urllib3/util/url.py:21:86: SyntaxError: PATH_CHARS = abnf_regexp.UNRESERVED_CHARS_SET | abnf_regexp.SUB_DELIMITERS_SET | {':', '@', '/'}\nvenv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py:24:1: SyntaxError: \nvenv/lib/python3.7/site-packages/setuptools/_vendor/pyparsing.py:24:1: SyntaxError: \nvenv/lib/python3.7/site-packages/setuptools/dist.py:446:20: SyntaxError: k: v for k, v in attrs.items()\nvenv/lib/python3.7/site-packages/setuptools/pep425tags.py:86:35: SyntaxError: if not soabi and impl in {'cp', 'pp'} and hasattr(sys, 'maxunicode'):\nvenv/lib/python3.7/site-packages/setuptools/wheel.py:152:15: SyntaxError: for extra in dist.extras"
        }
    ],
    "verified": false
}
