{
    "docs": "https://docs.ansible.com/ansible/2.9/dev_guide/testing/sanity/symlinks.html",
    "results": [
        {
            "message": "The test `ansible-test sanity --test symlinks` [[explain](https://docs.ansible.com/ansible/2.9/dev_guide/testing/sanity/symlinks.html)] failed with 2 errors:",
            "output": "venv/bin/python:0:0: broken symlinks are not allowed\nvenv/bin/python3:0:0: broken symlinks are not allowed"
        }
    ],
    "verified": false
}
